{{- $USE_STANDALONE_MESH := .USE_STANDALONE_MESH }}
{{- $GATEWAY_CONTROLLER_NAME := "openshift.io/gateway-controller/v1" }}
{{- if eq $USE_STANDALONE_MESH "true" }}
  {{- $GATEWAY_CONTROLLER_NAME = "istio.io/gateway-controller" }}
{{- end }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: 
  name: gw{{.GW_NUM}}-i{{.Iteration}}
  labels: 
    app: scale-test
spec: 
  gatewayClassName: {{$GATEWAY_CLASS_NAME}}
  listeners:
{{- $numListeners := .NUM_LISTENERS | atoi }}
{{- range $index := until $numListeners }}
  {{- $listenerNum := add1 $index }}
  - allowedRoutes:
      namespaces:
        from: All
    hostname: api-{{ $listenerNum }}.{{ $.JobName }}.{{ $.KUADRANT_ZONE_ROOT_DOMAIN }}
    name: api-{{$listenerNum}}
    port: 80
    protocol: HTTP
{{- end }}
