apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: envoy-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ${LABEL}
      svc: envoy
    name: ${NAME}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ${LABEL}
        svc: envoy
    template:
      metadata:
        labels:
          app: ${LABEL}
          svc: envoy
      spec:
        containers:
        - args:
          - --config-path /usr/local/etc/envoy/envoy.yaml
          - --service-cluster front-proxy
          - --log-level info
          - --component-log-level filter:trace,http:debug,router:debug
          command:
          - /usr/local/bin/envoy
          image: ${ENVOY_IMAGE}
          name: envoy
          readinessProbe:
            httpGet:
              path: /ready
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 4
          ports:
          - containerPort: 8000
            name: web
          - containerPort: 8001
            name: admin
          volumeMounts:
          - mountPath: /usr/local/etc/envoy
            name: config
            readOnly: true
        volumes:
        - configMap:
            items:
            - key: envoy.yaml
              path: envoy.yaml
            name: ${NAME}
          name: config
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}
  spec:
    ports:
    - name: api
      port: 8000
      protocol: TCP
    selector:
      app: ${LABEL}
      svc: envoy
parameters:
- name: NAME
  description: "Name for the resources created"
  required: true
- name: LABEL
  description: "App label for all resources"
  required: true
- name: ENVOY_IMAGE
  required: true
