apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: httpbin
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
    labels:
      app: ${LABEL}
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: ${LABEL}
    template:
      metadata:
        labels:
          app: ${LABEL}
          deployment: ${NAME}
      spec:
        containers:
          - image: quay.io/jsmadis/httpbin:latest
            imagePullPolicy: IfNotPresent
            name: httpbin
            ports:
              - containerPort: 8080
- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
    labels:
      app: ${LABEL}
  spec:
    ports:
      - name: http
        port: 8080
        targetPort: 8080
    selector:
      app: ${LABEL}
      deployment: ${NAME}
parameters:
- name: NAME
  description: "Httpbin's name"
  required: true
- name: LABEL
  description: "App label for all resources"
  required: true
- name: REPLICAS
  description: "Number of httpbin replicas"
  required: true
  value: "1"
