default:
  skip_cleanup: false
  dynaconf_merge: true
  openshift:
    project: "authorino"
  cfssl: "cfssl"
  rhsso:
    test_user:
      username: "testUser"
      password: "testPassword"
  authorino:
    deploy: true