default:
  skip_cleanup: false
  dynaconf_merge: true
  tools:
    project: "tools"
  cfssl: "cfssl"
  rhsso:
    username: "admin"
    test_user:
      username: "testUser"
      password: "testPassword"
  authorino:
    deploy: true
    log_level: "debug"
  envoy:
    image: "docker.io/envoyproxy/envoy:v1.23-latest"