default:
  dynaconf_merge: true
  cluster: {}
  kuadrantctl: "kuadrantctl"
  tools:
    project: "tools"
  cfssl: "cfssl"
  keycloak:
    username: "admin"
    test_user:
      username: "testUser"
      password: "testPassword"
  service_protection:
    system_project: "kuadrant-system"
    project: "kuadrant"
    project2: "kuadrant2"
    envoy:
      image: "quay.io/phala/envoy:v1.28-latest"
    gateway:
       project: "istio-system"
       name: "istio-ingressgateway"
    authorino:
      deploy: true
      log_level: "debug"
  control_plane:
    additional_clusters: []
    managedzone: "aws-mz"
    issuer:
      name: "selfsigned-issuer"
      kind: "ClusterIssuer"
  letsencrypt:
    issuer:
      name: "letsencrypt-staging-issuer"
      kind: "Issuer"
