default:
  skip_cleanup: false
  dynaconf_merge: true
  cfssl: "cfssl"
  rhsso:
    username: "admin"
    test_user:
      username: "testUser"
      password: "testPassword"
  authorino:
    deploy: true