apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials-{{.UUID}}-i{{.Iteration}}
  labels:
    app: max-gateway-listeners-scale-test
data:
  azure.json: {{ .AZURE_CONFIG_JSON }}
type: kuadrant.io/azure
