apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials-{{.UUID}}-i{{.Iteration}}
  labels:
    app: max-gateway-listeners-scale-test
data:
  GOOGLE: {{ .GCP_CONFIG_JSON }}
  PROJECT_ID: {{ .GCP_PROJECT_ID }}
type: kuadrant.io/gcp

