---
kind: Secret
apiVersion: v1
metadata:
  name: aws-credentials
  labels:
    app: scale-test
data:
  AWS_ACCESS_KEY_ID: your-base64-encoded-value
  AWS_REGION: your-base64-encoded-value
  AWS_SECRET_ACCESS_KEY: your-base64-encoded-value
type: kuadrant.io/aws
