{{- $KUADRANT_ZONE_ROOT_DOMAIN := .KUADRANT_ZONE_ROOT_DOMAIN }}
{{- $NUM_LISTENERS := .NUM_LISTENERS }}
---
metricsEndpoints: 
  - endpoint: {{ .PROMETHEUS_URL }}
    token: {{ .PROMETHEUS_TOKEN }}
    metrics: 
    - ./metrics.yaml
{{ if .OS_INDEXING }}
    indexer:
      type: opensearch
      esServers: ["{{ .ES_SERVER }}"]
      insecureSkipVerify: true
      defaultIndex: kube-burner
{{ else }}
    indexer:
      type: local
      metricsDirectory: ./metrics
{{ end }}
global:
{{ if .SKIP_CLEANUP }}
  gc: false
{{ else }}
  gc: true
{{ end }}
jobs: 
  - name: scale-test-preparations
    jobIterations: 1
    qps: 1
    burst: 1
    namespacedIterations: true
    namespace: scale-test
    waitWhenFinished: true
    objects:
      - objectTemplate: ./httpbin-deployment.yaml
        kind: Deployment
        replicas: 1
        waitOptions:
          forCondition: "Available"
          customStatusPath: ".conditions[].type"
      - objectTemplate: ./httpbin-service.yaml
        kind: Service
        replicas: 1
      - objectTemplate: ./aws-credentials.yaml
        kind: Secret
        replicas: 1
        inputVars:
          KUADRANT_AWS_ACCESS_KEY_ID: "{{ .KUADRANT_AWS_ACCESS_KEY_ID }}"
          KUADRANT_AWS_REGION: "{{ .KUADRANT_AWS_REGION }}"
          KUADRANT_AWS_SECRET_ACCESS_KEY: "{{ .KUADRANT_AWS_SECRET_ACCESS_KEY }}"
      - objectTemplate: ./person-secret.yaml
        kind: Secret
        replicas: 1
        inputVars:
          person: "alice"
      - objectTemplate: ./person-secret.yaml
        kind: Secret
        replicas: 1
        inputVars:
          person: "bob"
  - name: scale-test-main
    jobIterations: 1
    qps: 1
    burst: 1
    jobPause: 2m
    namespacedIterations: true
    namespace: scale-test
    waitWhenFinished: true
    objects:
{{- $numGWs := .NUM_GWS | atoi }}
{{- range $index := until $numGWs }}
  {{- $GW_NUM := add1 $index }}
      - objectTemplate: ./gw.yaml
        replicas: 1
        waitOptions:
          forCondition: Programmed
          customStatusPath: ".conditions[].type"
        inputVars:
          KUADRANT_ZONE_ROOT_DOMAIN: "{{$KUADRANT_ZONE_ROOT_DOMAIN}}"
          NUM_LISTENERS: "{{$NUM_LISTENERS}}"
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: ./gw-tls-policy.yaml
        replicas: 1
        waitOptions:
          forCondition: Enforced
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: ./gw-dns-policy.yaml
        replicas: 1
        waitOptions:
          forCondition: Enforced
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: ./gw-rlp.yaml
        replicas: 1
        waitOptions:
          forCondition: Accepted
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
      - objectTemplate: ./gw-auth-policy.yaml
        replicas: 1
        waitOptions:
          forCondition: Accepted
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
  {{- range $index := until ($NUM_LISTENERS | atoi)}}
    {{- $LISTENER_NUM := add1 $index }}
      - objectTemplate: ./httproute.yaml
        replicas: 1
        waitOptions:
          forCondition: Accepted
          customStatusPath: ".conditions[].type"
        inputVars:
          KUADRANT_ZONE_ROOT_DOMAIN: "{{$KUADRANT_ZONE_ROOT_DOMAIN}}"
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
      - objectTemplate: ./httproute-rlp.yaml
        replicas: 1
        waitOptions:
          forCondition: Enforced
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
      - objectTemplate: ./httproute-auth-policy.yaml
        replicas: 1
        waitOptions:
          forCondition: Enforced
          customStatusPath: ".conditions[].type"
        inputVars:
          GW_NUM: "{{$GW_NUM}}"
          LISTENER_NUM: "{{$LISTENER_NUM}}"
  {{- end }}
{{- end }}
{{ if .SKIP_CLEANUP }}
# nothing to do if cleanup is skipped
{{ else }}
  - name: scale-test-safe-dnspolicy-cleanup
    jobType: delete
    jobIterations: 1
    namespacedIterations: true
    namespace: scale-test
    waitWhenFinished: true
    objects:
      - kind: DNSPolicy
        apiVersion: kuadrant.io/v1alpha1
        labelSelector: {kube-burner-job: scale-test-main}
{{ end }}
