{{- $GW_NUM := .GW_NUM }}
{{- $LISTENER_NUM := .LISTENER_NUM }}
apiVersion: kuadrant.io/v1beta3
kind: AuthPolicy
metadata:
  name: httproute-auth-policy-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{ .Iteration }}
  labels: 
    app: scale-test
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: httproute-gw{{$GW_NUM}}-l{{$LISTENER_NUM}}-i{{ .Iteration }}
  rules:
    authorization:
      allow-all:
        opa:
          rego: "allow = true"
