apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: 
  name: scale-test-{{.Iteration}}
  labels: 
    app: scale-test
spec:
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: scale-test-{{.Iteration}}
  hostnames:
  - "api-{{.Iteration}}.scale-test-{{.Iteration}}.{{ .KUADRANT_ZONE_ROOT_DOMAIN }}"
  rules:
  - backendRefs:
    - group: ''
      kind: Service
      name: httpbin
      port: 8080
      weight: 1
    matches:
      - path:
          type: PathPrefix
          value: /
